on: [push]

jobs:
  all_cross:
    name: opencl/release/macos14
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        brew update
        brew install autoconf automake libtool gnu-sed

        export PATH="/opt/homebrew/opt/libtool/libexec/gnubin:$PATH"
        git clone --depth 1 https://github.com/BOINC/boinc.git
        cd ./boinc
        ./_autosetup
        ./configure --disable-server --disable-manager --disable-client CXXFLAGS="-O3 "
        make -j

    - name: build
      run: |
        make linux
        make boinc_lin
    - uses: actions/upload-artifact@v4
      with:
       name: ${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}.all
       path: ./repeatdecor-cl*